name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install poetry project
      run: poetry install
    - name: Format
      run: poetry run ruff format --check
    - name: Lint
      run: poetry run ruff check --extend-select I
    - name: Run pyright
      run: poetry run pyright
    - name: Run pytest
      run: poetry run pytest
